# Generated by Django 4.2.7 on 2023-12-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', unpack_ipv4=True),
        ),
    ]
