# Generated by Django 4.2.7 on 2023-12-20 05:53

from django.db import migrations, models
import empfiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=empfiles.models.user_file_upload)),
                ('file_description', models.CharField(default='-', max_length=200, null=True)),
            ],
        ),
    ]
