# Generated by Django 4.2.7 on 2023-12-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroupdevice',
            name='action',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
