# Generated by Django 4.2.7 on 2023-12-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employeegroupdevice_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
