# Generated by Django 4.2.7 on 2023-12-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_shift_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroupdevice',
            name='job_start_date',
            field=models.DateTimeField(auto_now_add=True, max_length=100, null=True),
        ),
    ]
