# Generated by Django 4.2.7 on 2024-01-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_gruop_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='gruop_name',
            new_name='group_name',
        ),
    ]
