# Generated by Django 4.2.7 on 2024-01-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_remove_employee_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='group_name',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
    ]
