# Generated by Django 4.2.7 on 2024-01-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employee_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='group_name',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
