# Generated by Django 4.2.7 on 2024-01-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_log_department_name_log_designation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='last_synced',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
