# Generated by Django 4.2.7 on 2023-12-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivelog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
