# Generated by Django 4.2.7 on 2023-12-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100, unique=True)),
                ('role_description', models.CharField(default='-', max_length=200, null=True)),
            ],
        ),
    ]
