# Generated by Django 4.2.7 on 2023-12-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftManagement',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_beginning', models.TimeField(default='00:00:00')),
                ('shift_end', models.TimeField(default='00:00:00')),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('shift_name', models.CharField(default='-', max_length=100, null=True)),
            ],
        ),
    ]
