# Generated by Django 4.2.7 on 2024-01-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0002_shiftassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassign',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shiftassign',
            name='shift_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
