# Generated by Django 4.2.7 on 2024-01-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpdev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdevice',
            name='device_name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='groupdevice',
            name='group_name',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
