# Generated by Django 4.2.7 on 2023-12-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('Remaks', models.CharField(default='-', max_length=100, null=True)),
            ],
        ),
    ]
