# Generated by Django 4.2.7 on 2023-12-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncInfoTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('syncTime', models.DateTimeField()),
                ('employee_id', models.CharField(default='SYSTEM', max_length=100)),
            ],
        ),
    ]
