# Generated by Django 4.2.7 on 2023-12-20 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='-', max_length=100, null=True)),
                ('InTime', models.DateTimeField(null=True)),
                ('OutTime', models.DateTimeField(null=True)),
                ('total_work_minutes', models.IntegerField(default=0, null=True)),
                ('cumalative_work_minutes', models.IntegerField(default=0, null=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devices')),
            ],
        ),
    ]
