# Generated by Django 4.2.7 on 2023-12-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_report', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='delay_minutes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
