# Generated by Django 4.2.7 on 2024-01-01 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
        ('department', '0001_initial'),
        ('attendance_report', '0003_attendancereport_delay_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designation.designation'),
        ),
    ]
