# Generated by Django 4.2.7 on 2024-01-02 08:55

import attendance_report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_report', '0005_attendancereport_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='date',
            field=models.DateField(default=attendance_report.models.get_default_date, null=True),
        ),
    ]
